<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Register extends Model
{
    use HasFactory;

    protected $table = 'register';

    protected $primaryKey = 'id_reg';

    public $incrementing = true;

    protected $keyType = 'int';

    protected $fillable = [
        'id_reg',
        'gen_no_reg',
        'no_dpa',
        'tanggal',
        'kd_prog',
        'kd_keg',
        'kd_subkeg',
        'urai_prog',
        'urai_keg',
        'urai_subkeg',
        'kd_rekbel',
        'urai_rekbel',
        'set_gu_sp2d',
        'tgl_bukti',
        'jenis_tu',
        'jenis_a2',
        'j_transaksi',
        'nom_bruto',
        'keperluan',
        'nama_penerima',
        'bank_penerima',
        'norek_penerima',
        'npwp_penerima',
        'alamat_penerima',
        't_pajak',
        'jpajak_1',
        'kd_pot1',
        'id_bill1',
        'nom_pajak1',
        'jpajak_2',
        'kd_pot2',
        'id_bill2',
        'nom_pajak2',
        'time_create',
        'id_create',
        'time_update',
        'id_update',
        'id_kom1',
        'id_kom2',
        'id_kom3',
        'id_kom4',
        'id_kom5',
        'id_kom6',
        'id_kom7',
        'id_kom8',
        'id_kom9',
        'id_kom10',
        'id_kom11',
        'id_kom12',
        'id_kom13',
        'id_kom14',
        'id_kom15',
        'id_kom16',
        'id_kom17',
        'id_kom18',
        'id_kom19',
        'id_kom20',
        'id_kom21',
        'id_kom22',
        'qty_kom1',
        'qty_kom2',
        'qty_kom3',
        'qty_kom4',
        'qty_kom5',
        'qty_kom6',
        'qty_kom7',
        'qty_kom8',
        'qty_kom9',
        'qty_kom10',
        'qty_kom11',
        'qty_kom12',
        'qty_kom13',
        'qty_kom14',
        'qty_kom15',
        'qty_kom16',
        'qty_kom17',
        'qty_kom18',
        'qty_kom19',
        'qty_kom20',
        'qty_kom21',
        'qty_kom22',
        'hrg_kom1',
        'hrg_kom2',
        'hrg_kom3',
        'hrg_kom4',
        'hrg_kom5',
        'hrg_kom6',
        'hrg_kom7',
        'hrg_kom8',
        'hrg_kom9',
        'hrg_kom10',
        'hrg_kom11',
        'hrg_kom12',
        'hrg_kom13',
        'hrg_kom14',
        'hrg_kom15',
        'hrg_kom16',
        'hrg_kom17',
        'hrg_kom18',
        'hrg_kom19',
        'hrg_kom20',
        'hrg_kom21',
        'hrg_kom22',
        'id_kom23',
        'qty_kom23',
        'hrg_kom23',
        'id_kom24',
        'qty_kom24',
        'hrg_kom24',
        'id_kom25',
        'qty_kom25',
        'hrg_kom25',
        'tot_komp10',
        'tot_komp11',
        'tot_komp12',
        'tot_komp13',
        'tot_komp14',
        'tot_komp15',
        'tot_komp16',
        'tot_komp17',
        'tot_komp18',
        'tot_komp19',
        'tot_komp20',
        'tot_komp21',
        'tot_komp22',
        'cek_sah',
        'Ket-Pajak1',
        'Ket-Pajak2',
        'tgl_setor',
        'ntpn1',
        'ntpn2',
        'npwp_setor',
        'nom_netto',
        'netto_terbilang',
        'bruto_terbilang',
        'kode_skpd',
        'nama_skpd',
        'nama_pa',
        'nip_pa',
        'nama_pptk',
        'nip_pptk',
        'nama_bendahara',
        'nip_bendahara',
        'verifikator1',
        'verifikator2',
    ];

    public function detailBelanja()
    {
        return $this->hasMany(
            DetailBelanja::class,
            'id_reg',   // FK di detail_belanja
            'id_reg'    // PK di register
        );
    }
}
